In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVR

In [2]:
df=sns.load_dataset('tips')

In [3]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [4]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [5]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [6]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [7]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

## My observation  from this dataset is perform the label encoding for sex,time,smoker because they are binary classification and perform OneHotEncoding fo the day because there are many categrouries.

In [8]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
from sklearn.model_selection import train_test_split
X=df[['tip','sex','smoker','day','time','size']]
y=df['total_bill']

In [10]:
# split the data into train and test data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [11]:
X_train.head()

,tip,sex,smoker,day,time,size
58,1.76,Male,Yes,Sat,Dinner,2
1,1.66,Male,No,Sun,Dinner,3
2,3.50,Male,No,Sun,Dinner,3
68,2.01,Male,No,Sat,Dinner,2
184,3.00,Male,Yes,Sun,Dinner,2


## why we performing feature encoding after split because of data leakage that train data have no idea about the test data

In [12]:
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [ ]:
l1=LabelEncoder()
l2=LabelEncoder()
l3=LabelEncoder()


In [14]:
X_train['sex']=l1.fit_transform(X_train['sex'])
X_train['smoker']=l2.fit_transform(X_train['smoker'])
X_train['time']=l3.fit_transform(X_train['time'])

In [15]:
X_train.head()

,tip,sex,smoker,day,time,size
58,1.76,1,1,Sat,0,2
1,1.66,1,0,Sun,0,3
2,3.50,1,0,Sun,0,3
68,2.01,1,0,Sat,0,2
184,3.00,1,1,Sun,0,2


## only we do transform because the train data dont know the test datas

In [16]:
X_test['sex']=l1.transform(X_test['sex'])
X_test['smoker']=l2.transform(X_test['smoker'])
X_test['time']=l3.transform(X_test['time'])

In [17]:
X_test.head()

,tip,sex,smoker,day,time,size
162,2.00,0,0,Sun,0,3
60,3.21,1,1,Sat,0,2
61,2.00,1,1,Sat,0,2
63,3.76,1,1,Sat,0,4
69,2.09,1,1,Sat,0,2


## Perfom OneHotEncoding on the Day feature

In [18]:
## Onehot encoding--- ColumnTrnasformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [19]:
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')


In [20]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [21]:
X_test=ct.transform(X_test)

In [22]:
X_train

array([[ 1.  ,  0.  ,  0.  ,  1.76,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.66,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.01,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  4.  ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.2 ,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  4.  ,  1.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  5.  ,  1.  ,  0.  ,  1.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.75,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.12,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  5.  ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  4.  ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.

In [23]:
X_test

array([[0.  , 1.  , 0.  , 2.  , 0.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.76, 1.  , 1.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 2.09, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.6 , 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.65, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.09, 0.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 1.68,

In [24]:
svr=SVR()
svr.fit(X_train,y_train)

,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,tol,0.001
,C,1.0
,epsilon,0.1
,shrinking,True
,cache_size,200
,verbose,False
,max_iter,-1


In [25]:
y_pred=svr.predict(X_test)
y_pred

array([16.63987262, 17.80422691, 14.49145093, 24.62866424, 14.67173361,
       22.67410166, 19.04664805, 28.29108519, 23.75972181, 21.46546953,
       24.86896212, 17.67206073, 13.44339231, 22.32034304, 19.75694037,
       14.95399101, 13.8566174 , 13.39304164, 21.2171004 , 17.63874958,
       14.32207633, 15.49171819, 14.19580813, 13.3369827 , 29.65235934,
       13.8566174 , 17.37720431, 21.38260597, 14.76962827, 30.02183062,
       28.64203024, 28.03548476, 14.79770992, 15.92806049, 17.56421584,
       13.35938349, 20.52423608, 14.51606288, 20.71506125, 22.18900247,
       16.70814899, 21.52705566, 13.2124233 , 24.44552357, 14.05257741,
       14.13643952, 18.52010744, 14.79770992, 13.74271464, 18.54833482,
       20.82086506, 29.78470039, 19.41806679, 27.8646883 , 13.01786739,
       16.91813134, 14.06890087, 14.15277698, 17.87180292, 13.83656792,
       17.37317545])

In [26]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.46028114561159283
4.1486423210190235


## Hyperparameter Tuning using GridSearch CV

In [27]:
from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

In [28]:
grid=GridSearchCV(SVR(),param_grid=param_grid,scoring='accuracy',refit=True,verbose=3)

In [29]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ..........C=0.1, gamma=1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=0.1, kernel=rbf;, score=nan total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=0.01, kernel=rbf;, score=nan total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=0.01, kernel=r

,estimator,SVR()
,param_grid,"{'C': [0.1, 1, ...], 'gamma': [1, 0.1, ...], 'kernel': ['rbf']}"
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,None
,verbose,3
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,kernel,'rbf'


In [30]:
grid.best_params_

{'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}

In [31]:
grid_prediction=grid.predict(X_test)

In [32]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,grid_prediction))
print(mean_absolute_error(y_test,grid_prediction))

0.003483876096391114
6.598137329385286


In [33]:
from sklearn.naive_bayes import GaussianNB


In [34]:
X=df[['tip','sex','smoker','day','size','total_bill']]
y=df['time']

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [39]:
X_train

,tip,sex,smoker,day,size,total_bill
58,1.76,Male,Yes,Sat,2,11.24
1,1.66,Male,No,Sun,3,10.34
2,3.50,Male,No,Sun,3,21.01
68,2.01,Male,No,Sat,2,20.23
184,3.00,Male,Yes,Sun,2,40.55
...,...,...,...,...,...,...
64,2.64,Male,No,Sat,3,17.59
15,3.92,Male,No,Sun,2,21.58
228,2.72,Male,No,Sat,2,13.28
125,4.20,Female,No,Thur,6,29.80


In [40]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split

X = df[['tip', 'sex', 'smoker', 'day', 'size', 'total_bill']]
y = df['time']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import LabelEncoder

sex_encoder = LabelEncoder()
smoker_encoder = LabelEncoder()

X_train['sex'] = sex_encoder.fit_transform(X_train['sex'])
X_train['smoker'] = smoker_encoder.fit_transform(X_train['smoker'])

X_test['sex'] = sex_encoder.transform(X_test['sex'])
X_test['smoker'] = smoker_encoder.transform(X_test['smoker'])

time_encoder = LabelEncoder()

y_train = time_encoder.fit_transform(y_train)
y_test = time_encoder.transform(y_test)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('day_encoder', OneHotEncoder(drop='first'), ['day'])
    ],
    remainder='passthrough'
)

X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

print("Feature Names:")
print(ct.get_feature_names_out())

print("\nX_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)

print("\ny_train Sample:")
print(y_train[:10])

print("\ny_test Sample:")
print(y_test[:10])

Feature Names:
['day_encoder__day_Sat' 'day_encoder__day_Sun' 'day_encoder__day_Thur'
 'remainder__tip' 'remainder__sex' 'remainder__smoker' 'remainder__size'
 'remainder__total_bill']

X_train Shape: (195, 8)
X_test Shape: (49, 8)

y_train Sample:
[0 0 0 0 1 0 1 0 0 0]

y_test Sample:
[0 0 0 0 1 0 1 1 0 0]


In [41]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)
gnb_pred=gnb.predict(X_test)

In [42]:
from sklearn.metrics import confusion_matrix,classification_report,mean_absolute_error
print(confusion_matrix(y_test,gnb_pred))
print(classification_report(y_test,gnb_pred))

print(mean_absolute_error(y_test,gnb_pred))



[[32  2]
 [ 0 15]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        34
           1       0.88      1.00      0.94        15

    accuracy                           0.96        49
   macro avg       0.94      0.97      0.95        49
weighted avg       0.96      0.96      0.96        49

0.04081632653061224


## I am getting 96% accuracy